[package]
name = "holofoil"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
bytes.workspace = true
wgpu.workspace = true

[workspace]
members = ["examples/*"]

[workspace.dependencies]
holofoil = { path = "." }

bytemuck = "1"
bytes = "1"
wgpu = "26"
winit = "0.30"

png = "0.18"
pollster = "0.4"
notify = "8"
console_error_panic_hook = "0.1"
wasm-bindgen-futures = "0.4"
web-time = "1"
web-sys = "0.3"
